name: Deploy Maven

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Get Change Type
        id: change-type
        shell: bash
        run: |
          change_type=$(git log -1 --merges --oneline | grep -Pio "\b(major|minor|patch|hotfix)(?=\/)")
          echo "type=$change_type" >> $GITHUB_OUTPUT
          echo "$change_type"

      - name: Bump ${{ steps.change-type.outputs.type }} version
        id: semver
        shell: bash
        run: |
          pom="./xqlite-java/pom.xml"
          get_version=$(python ./xqlite-java/get_version.py $pom)
          version=$(python ./bump_version.py $get_version ${{ steps.change-type.outputs.type }})
          python ./xqlite-java/set_version.py $pom $version
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "$version"

      - name: Render settings.xml with GitHub secrets
        shell: bash
        run: |
          export MAVEN_USERNAME=plycos
          export MAVEN_TOKEN=${{ secrets.REGISTRY_TOKEN }}
          envsubst < ./xqlite-java/settings.xml > ./xqlite-java/maven-settings.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to XQLite Maven Registry
        uses: docker/build-push-action@v6
        with:
          push: false
          context: './xqlite-java'
          file: './xqlite-java/Dockerfile.build'
          target: 'deploy'
          secret-files: |
            "MAVEN_SETTINGS=./xqlite-java/maven-settings.xml"
      #          cache-from: type=gha
      #          cache-to: type=gha,mode=max

      - name: Bump to Snapshot ${{ steps.semver.outputs.version }}
        if: success()
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          version=${{ steps.semver.outputs.version }}-SNAPSHOT
          python ./xqlite-java/set_version.py ./xqlite-java/pom.xml $version
          git add ./xqlite-java/pom.xml
          git commit -m "[skip ci] Bump to Snapshot version $version"

      - name: Push Snapshot Commit
        if: success()
        shell: bash
        run: git push origin HEAD:master
